### ISSUE TITLE
-address requires the correct path 

### ISSUE THREAD

**Issue by adamdecaf** [rot256/fugl#2]
I was trying this out locally and ran into an issue where the `-address` flag requires the user to properly specify `/submit` or `/latest`, etc. This was a bit confusing to me as some other apps will append on the api path (and typically assume the address is a hostname or has path for load balancing).

I think it'd be pretty simple to append on the proper path in `cmd/client/op_*.go` if it's not there. I can submit a PR for this if you'd like.

This also uncovered a panic where `/submit` was not properly checking the canary was non-nil before trying to parse parts of it. -- https://github.com/rot256/fugl/pull/3

client:
```
$ ./fugl-client -address http://localhost:8080/submit --operation pull -debug
flags: {./temp.proof     0s  http://localhost:8080/submit ./manifest.toml pull true false false}
Failed connect to address: Get http://localhost:8080/submit: EOF%
```

server:
```
canary = <nil>
2017-02-17 12:28:14 CST http: panic serving [::1]:51361: runtime error: invalid memory address or nil pointer dereference
goroutine 10 [running]:
net/http.(*conn).serve.func1(0xc420088d20)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1721 +0xd0
panic(0x12ceb20, 0x148f400)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:489 +0x2cf
main.(*SubmitHandler).ServeHTTP(0xc42000e0c0, 0x146d180, 0xc4201121c0, 0xc42000be00)
	/Users/adam/src/go/src/github.com/rot256/fugl/cmd/server/handlers.go:75 +0x225
net/http.(*ServeMux).ServeHTTP(0xc42001b5c0, 0x146d180, 0xc4201121c0, 0xc42000be00)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc42009c2c0, 0x146d180, 0xc4201121c0, 0xc42000be00)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc420088d20, 0x146d780, 0xc420015200)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2668 +0x2ce
```

**Comment by rot256** [comment]
I thought about this as well. It may be more intuitive and it is a straightforward addition.
Do you think the protocol should still be specified by the user?

With regards to the latter issue, this project definitely needs tests.

**Comment by adamdecaf** [comment]
I think the protocol can default to https if not specified.

**Comment by rot256** [comment]
This has now been implemented. Let me know if you have any comments.

**Comment by adamdecaf** [comment]
Where is createURL defined? I'm not seeing it.

https://github.com/rot256/fugl/search?utf8=%E2%9C%93&q=createURL

**Comment by rot256** [comment]
Pushed. I feel like an idiot for missing it.

**Comment by adamdecaf** [comment]
@rot256 No worries. It looks good. I've had to do that same scheme/host/path trick also. It's a bit annoying.

I was thinking that having some CI around this would be nice. Just for PR's and the like? It'd probably be better to add some tests first. I can get some going.
