### ISSUE TITLE
'resign' command on client

### ISSUE THREAD

**Issue by adamdecaf** [rot256/fugl#5]
I was setting this up locally and noticed it might be handy for the client to have an 'resign' operation. This would allow people to store their canary(s) somewhere and update them to push rather than re-create each time. (Which would be a copy/paste of the contents.)

**Comment by rot256** [comment]
Maybe, could you elaborate a bit more?

If the action can be completed using a simple `$> mv a.proof b.proof` then I would prefer to keep the client simple and omit the feature.

**Comment by adamdecaf** [comment]
I think the better option is just to edit and maintain the `manifest.toml` instead.
